#!/usr/bin/env bash

# This script will launch the command given as an argument if not yet running
# Else it'll give focus to the command window

# Author: Piotr Miller
# e-mail: nwg.piotr@gmail.com
# Website: http://nwg.pl
# Project: https://github.com/nwg-piotr/tint2-executors
# License: GPL3

# Dependencies: `xorg-xprop`, `wmctrl`
# Usage: ./rof [-P process_name] command

if [[ "$1" == *"-P"* ]]; then
   id=$(xprop -name $2 | grep PID | awk '{print $3}')
   echo "id: "$id
   if [ ! -z "$id" ]; then
       name=$(wmctrl -lp | grep $id | awk '{print $5}')
       echo "name: "$name
       wmctrl -a $name
   else
       $3 $4 $5
   fi

else
   id=$(xprop -name $1 | grep PID | awk '{print $3}')
   if [ ! -z "$id" ]; then
       name=$(wmctrl -lp | grep $id | awk '{print $4}')
       wmctrl -a $name
   else
       $1 $2 $3
   fi
fi