#!/usr/bin/env bash

# This script will launch the command given as an argument if not yet running
# Else it'll give focus to the command window

# Usage:
# ./rof [-P process_name] command

# Examples:
# ./rof pavucontrol
# ./rof -P zenity ~/tint2-executors/zenity-set-volume.sh

# In the 2nd case the process name is `zenity` and varies from the command itself

# Author: Piotr Miller
# e-mail: nwg.piotr@gmail.com
# Website: http://nwg.pl
# Project: https://github.com/nwg-piotr/tint2-executors
# License: GPL3

# Dependencies: `xorg-xprop`, `wmctrl`


if [[ "$1" == *"-P"* ]]; then
   id=$(xprop -name $2 | grep PID | awk '{print $3}')
   if [ ! -z "$id" ]; then
       name=$(wmctrl -lp | grep $id | awk '{print $5" "$6}')
       wmctrl -a $name
   else
       ${@:3}
   fi

else
   id=$(xprop -name $1 | grep PID | awk '{print $3}')
   if [ ! -z "$id" ]; then
       name=$(wmctrl -lp | grep $id | awk '{print $5" "$6}')
       wmctrl -a $name
   else
       $@
   fi
fi