#!/usr/bin/env bash

# This script will launch the command given as an argument if not yet running
# Else it'll give focus to the command window

# Author: Piotr Miller
# e-mail: nwg.piotr@gmail.com
# Website: http://nwg.pl
# Project: https://github.com/nwg-piotr/tint2-executors
# License: GPL3

# Usage:
# ./rof [-P process_name] command

# Examples:
# ./rof pavucontrol
# ./rof -P zenity ~/tint2-executors/zenity-set-volume.sh
# In the 2nd case the process name is `zenity` and varies from the command itself

# Dependencies: `xorg-xprop`, `wmctrl`

if [[ $(which xprop) != *"/xprop"* ]]; then
    echo -e "\nDependencies: xorg-xprop package missing...\n"
    exit
fi
if [[ $(which wmctrl) != *"/wmctrl"* ]]; then
    echo -e "\nDependencies: wmctrl package missing...\n"
    exit
fi

if [ ! -z "$1" ]; then

    if [[ "$1" == "-P" ]]; then

       if [ "$#" -ge 3 ]; then
           pid=$(xprop -name $2 | grep PID | awk '{print $3}')
           if [ ! -z "$pid" ]; then
               name=$(wmctrl -lp | grep $pid | awk '{print $1}')
               wmctrl -a ${name}
           else
               ${@:3}
           fi
       else
           echo -e "\nShould be: rof -P process_name command\n"
       fi

    elif [[ "$1" == *"-h"* ]] || [[ "$1" == *"--help"* ]]; then
       echo -e "\nUsage: rof [-P process_name] command\n"

    else

       pid=$(xprop -name $1 | grep PID | awk '{print $3}')
       echo "pid=$pid"
       if [ ! -z "$pid" ]; then
           name=$(wmctrl -lp | grep ${pid} | awk '{print $1}')
           echo "Set focus on window id $name"
           wmctrl -i -a ${name}
       else
           echo "Launch a new instance of $1"
           sh -c "$@ &"
       fi
    fi
else
    echo -e "\nUsage: rof [-P process_name] command\n"
fi