#!/bin/sh

if [[ $1 == --desktop ]]; then
    exec /usr/lib/t2ec/desktop.py $2
elif [[ $1 == --bbswitch ]]; then
    exec /usr/lib/t2ec/bbswitch-status-temp.sh
elif [[ $1 == --volume ]]; then
    exec /usr/lib/t2ec/volume-icon.sh $2
else
    echo "Unknown command"
fi
